version: 2
 
seeds:
  - name: lkp_divisons
    config:
      schema: "{{env_var('DBT_LOOKUPSCHEMA','LOOKPUP_DEV')}}"

  - name: lkp_category
    config:
      schema: "{{env_var('DBT_LOOKUPSCHEMA','LOOKPUP_DEV')}}"
      
  - name: lkp_shippers
    config:
      schema: "{{env_var('DBT_LOOKUPSCHEMA','LOOKPUP_DEV')}}"
